// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwUr4ZGAQC9NM3yVqkacskLGlwrrdGO8',
    appId: '1:339720549396:web:79befb48c555e4a635e301',
    messagingSenderId: '339720549396',
    projectId: 'miniproject-fc41e',
    authDomain: 'miniproject-fc41e.firebaseapp.com',
    databaseURL: 'https://miniproject-fc41e-default-rtdb.firebaseio.com',
    storageBucket: 'miniproject-fc41e.firebasestorage.app',
    measurementId: 'G-YEEJ5N61T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAspo3Jm7F3YSAmeFyTUmqby5CiYXfMTos',
    appId: '1:339720549396:android:0ea40848de720f0535e301',
    messagingSenderId: '339720549396',
    projectId: 'miniproject-fc41e',
    databaseURL: 'https://miniproject-fc41e-default-rtdb.firebaseio.com',
    storageBucket: 'miniproject-fc41e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7AobxI-8lSSdF_Vyj6vFW2FCf3DwJWw',
    appId: '1:339720549396:ios:cd48b65ee11b75e335e301',
    messagingSenderId: '339720549396',
    projectId: 'miniproject-fc41e',
    databaseURL: 'https://miniproject-fc41e-default-rtdb.firebaseio.com',
    storageBucket: 'miniproject-fc41e.firebasestorage.app',
    iosBundleId: 'com.example.elcbMonitor',
  );

}